### ISSUE TITLE
Problema starting Daemon

### ISSUE THREAD

**Issue by Bassysta** [Icinga/icingaweb2-module-vsphere#26]
Hi.
Hope to have open the issue in the right way. You already reply to me in another issue where i wrongly commented, but i'm still stuck so i come back with more info.

I'm new with icinga and It's modules, so please speak to me like you speak with a child.

When i try to start the service i recieved this message:

[root@localhost vspheredb]# systemctl start icinga-vspheredb
Job for icinga-vspheredb.service failed because the control process exited with error code. See "systemctl status icinga-vspheredb.service" and "journalctl -xe" for details.
[root@localhost vspheredb]# systemctl status icinga-vspheredb.service
● icinga-vspheredb.service - Icinga vSphereDB Daemon
   Loaded: loaded (/etc/systemd/system/icinga-vspheredb.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2018-12-11 07:40:58 EST; 6s ago
     Docs: https://icinga.com/docs/icinga-vsphere/latest/
  Process: 3568 ExecStart=/usr/bin/icingacli vspheredb daemon run (code=exited, status=217/USER)
 Main PID: 3568 (code=exited, status=217/USER)

Dec 11 07:40:58 localhost.localdomain systemd[1]: icinga-vspheredb.service: main process exited, code=exited, status=217/USER
Dec 11 07:40:58 localhost.localdomain systemd[1]: Failed to start Icinga vSphereDB Daemon.
Dec 11 07:40:58 localhost.localdomain systemd[1]: Unit icinga-vspheredb.service entered failed state.
Dec 11 07:40:58 localhost.localdomain systemd[1]: icinga-vspheredb.service failed.

and here my daemon starting error:

[root@localhost vspheredb]# /usr/bin/icingacli vspheredb daemon run
PHP Fatal error:  Uncaught Error: Call to undefined function Icinga\Module\Vspheredb\Daemon\posix_getpid() in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php:63
Stack trace:
#0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php(56): Icinga\Module\Vspheredb\Daemon\Daemon->detectProcessInfo()
#1 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(25): Icinga\Module\Vspheredb\Daemon\Daemon->__construct()
#2 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
#3 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#4 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#5 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#6 {main}
  thrown in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php on line 63

Fatal error: Uncaught Error: Call to undefined function Icinga\Module\Vspheredb\Daemon\posix_getpid() in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php:63
Stack trace:
#0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php(56): Icinga\Module\Vspheredb\Daemon\Daemon->detectProcessInfo()
#1 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(25): Icinga\Module\Vspheredb\Daemon\Daemon->__construct()
#2 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
#3 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#4 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#5 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#6 {main}
  thrown in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php on line 63

You already told me about a PHP problem, so here my installed plugins and version:

[root@localhost vspheredb]# php -v
PHP 7.0.32 (cli) (built: Sep 13 2018 16:50:42) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

Installed Packages:

[root@localhost tmp]# yum list installed | grep php
icingaweb2-vendor-lessphp.noarch 2.6.2-1.el7.icinga       @icinga-stable-release
mod_php70u.x86_64                7.0.32-1.ius.centos7     @ius
php-Icinga.noarch                2.6.2-1.el7.icinga       @icinga-stable-release
php70u-cli.x86_64                7.0.32-1.ius.centos7     @ius
php70u-common.x86_64             7.0.32-1.ius.centos7     @ius
php70u-mysqlnd.x86_64            7.0.32-1.ius.centos7     @ius
php70u-pdo.x86_64                7.0.32-1.ius.centos7     @ius
php70u-process.x86_64            7.0.32-1.ius.centos7     @ius
php70u-soap.x86_64               7.0.32-1.ius.centos7     @ius
rh-php71-php-cli.x86_64          7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-common.x86_64       7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-fpm.x86_64          7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-gd.x86_64           7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-intl.x86_64         7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-json.x86_64         7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-ldap.x86_64         7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-mbstring.x86_64     7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-pdo.x86_64          7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-pgsql.x86_64        7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-process.x86_64      7.1.8-1.el7              installed
rh-php71-php-xml.x86_64          7.1.8-1.el7              @centos-sclo-rh
rh-php71-php-zip.x86_64          7.1.8-1.el7              @centos-sclo-rh
rh-php71-runtime.x86_64          1-1.el7                  @centos-sclo-rh

Can you please tell me how to get out? as i already said i'm not really good with icinga and linux in general.

Thank you for yout patiance

**Comment by Bassysta** [comment]
Find problem  by myself, as you said i've installe the wrong php-process package.
have a nice day
