### ISSUE TITLE
import source does not work with vsphere 7.0

### ISSUE THREAD

**Issue by andreas-noethen** [Icinga/icingaweb2-module-vsphere#33]
vSphere Client Version 7.0.0.10600
php 7.3.20
Icinga Web 2 Version 2.8.1
vsphere 1.1.0

for import source > preview
the error is
```
Got 500: '<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>The session is not authenticated.</faultstring><detail><NotAuthenticatedFault xmlns="urn:vim25" xsi:type="NotAuthenticated"><object type="Folder">group-d1</object><privilegeId>System.View</privilegeId></NotAuthenticatedFault></detail></soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>'
```
___
```
#0 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/CurlLoader.php(184): Icinga\Module\Vsphere\CurlLoader->request(String, String, String, Array)
#1 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/SoapClient.php(55): Icinga\Module\Vsphere\CurlLoader->post(String, String, Array)
#2 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/SoapClient.php(36): Icinga\Module\Vsphere\SoapClient->doCurlRequest(String, String, String, Integer, Integer)
#3 [internal function]: Icinga\Module\Vsphere\SoapClient->__doRequest(String, String, String, Integer, Integer)
#4 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(110): SoapClient->__soapCall(String, Array)
#5 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(267): Icinga\Module\Vsphere\Api->soapCall(String, Array)
#6 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/ProvidedHook/Director/ImportSource.php(31): Icinga\Module\Vsphere\Api->logout()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(100): Icinga\Module\Vsphere\ProvidedHook\Director\ImportSource->fetchData()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#9 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#10 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(56): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#11 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(255): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator(Object(gipfl\IcingaWeb2\Url))
#12 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(146): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#19 {main}
```

module still works for other vsphere 6.x datasources 

hint to problem:
https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-esxi-vcenter-server-70-release-notes.html#miscellaneous-issues-known  >  HTTP requests from certain libraries to vSphere might be rejected

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this! Our requests are not rejected, the problem is that they're now sending `set-cookie` and used to send `Set-Cookie`. Guess they replaced their whole HTTP-Library/Stack. The bug is in our code, HTTP headers are case insensitive - you cannot bet on getting them in a certain format.

**Comment by Wintermute2k6** [comment]
ref/NC 742394

**Comment by Wintermute2k6** [comment]
Seems like the Issue is still persistent in some User locations. This might be due to different HTTP-Library/Stack Versions on VMWare Side in different VSphere Versions.
